language: ruby
before_install:
 - gem install bundler
 - bundle install

script: bundle exec rake

rvm:
  - 2.0
  - 2.1
  - 2.2
  - jruby
  - rbx-2

matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby
    - gemfile: gemfiles/active_model_4.0.gemfile
    - gemfile: gemfiles/active_model_edge.gemfile

gemfile:
  - gemfiles/active_model_4.0.gemfile
  - gemfiles/active_model_4.1.gemfile
  - gemfiles/active_model_4.2.gemfile
  - gemfiles/active_model_edge.gemfile
